//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinkelServiceLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInventoryEntity
    {
        public int Id { get; set; }
        public int InventoryEntityId { get; set; }
        public int ProductEntityId { get; set; }
    
        public virtual InventoryEntity InventoryEntity { get; set; }
        public virtual ProductEntity ProductEntity { get; set; }
    }
}
